### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by Abdullah-Ajeebi** [RealIndica/ES-Studio#3]

**Comment by RealIndica** [comment]
More information?

**Comment by Abdullah-Ajeebi** [comment]
It's missing dependency's, I'm not on my computer right now though.

**Comment by RealIndica** [comment]
> It's missing dependency's, I'm not on my computer right now though.

what dependencies are missing? all dependencies should already be included on github.

**Comment by RealIndica** [comment]
Dependencies have now been correctly uploaded and you should now be able to build.

6cf8558ef36260d6fb62d77af88dbe717b12cf8f
